import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
    },
    ctnIntro: {
        height: 400,
        with: '100%',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    imgIntro: {
        height: '100%',
        width: '100%',
    },
    ctnButtonBack: {
        position: 'absolute',
        top: 30,
        left: 10,
        zIndex: 20,
    },
    buttonBack: {
        paddingHorizontal: 8,
        paddingVertical: 8,
        backgroundColor: '#fff',
        borderRadius: 50,
    },
    body: {
        position: 'absolute',
        zIndex: 15,
        width: '100%',
        height: '100%',
    },
    marginTop: {
        marginTop: 400,
    },
    ctnInteract: {
        flexDirection: 'column',
        alignItems: 'center',
        paddingVertical: 28,
        borderBottomColor: '#ccc',
        borderBottomWidth: 1,
        backgroundColor: '#fff',
        paddingHorizontal: 16,
    },
    textRecipe: {
        fontFamily: 'Poly-Regular',
        fontSize: 32,
        marginBottom: 20,
        textAlign: 'center',
        width: '80%',
    },
    ctnRating: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    numberRating: {
        fontFamily: 'Poly-Regular',
        marginVertical: 10,
        fontSize: 18,
    },
    ctnSocialOnScroll: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        flexDirection: 'row',
        justifyContent: 'space-between',
        backgroundColor: '#fff',
        paddingHorizontal: 8,
        paddingBottom: 2,
        paddingTop: 20,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        zIndex: 100,
    },
    ctnSocial: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 12,
    },
    btnSocial: {
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 8,
        paddingVertical: 12,
        marginHorizontal: 12,
    },
    numberLike: {
        fontFamily: 'Poly-Regular',
        fontSize: 24,
        marginTop: 2,
        fontWeight: 'bold',
    },
    textSocial: {
        fontFamily: 'Poly-Regular',
        fontSize: 20,
        marginTop: 6,
    },
    ctnItem: {
        borderBottomColor: '#ccc',
        borderBottomWidth: 1,
        paddingVertical: 24,
        backgroundColor: '#fff',
    },
    ctnTime: {
        flexDirection: 'row',
        justifyContent: 'space-evenly',
        paddingHorizontal: 12,
        paddingVertical: 16,
        backgroundColor: '#fff5ea',
    },
    textTime: {
        fontFamily: 'Poly-Regular',
        fontSize: 18,
        fontWeight: 'bold',
        marginBottom: 4,
        textAlign: 'center',
    },
    headingReview: {
        flexDirection: 'row',
        width: '100%',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    textHeadingReview: {
        fontFamily: 'Poly-Regular',
        fontSize: 22,
    },
    ctnIngredients: {
        paddingTop: 16,
        paddingBottom: 24,
        borderBottomColor: '#ccc',
        borderBottomWidth: 1,
        paddingHorizontal: 16,
        backgroundColor: '#fff',
    },
    ctnAdjust: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 24,
    },
    numberAdjust: {
        fontFamily: 'Poly-Regular',
        fontWeight: 'bold',
        fontSize: 20,
    },
    adjustQuantity: {
        flexDirection: 'row',
        alignItems: 'center',
        marginRight: 16,
    },
    textAdjust: {
        fontFamily: 'Poly-Regular',
        fontSize: 24,
        marginHorizontal: 12,
    },
    btnAdjust: {
        paddingVertical: 8,
        paddingHorizontal: 16,
        backgroundColor: '#ede5dc',
        borderRadius: 8,
    },
    renderIngredients: {
        flexDirection: 'row',
        marginTop: 24,
        backgroundColor: '#fff',
    },
    itemLeft: {
        width: '25%',
    },
    itemRight: {
        width: '75%',
    },
    textIngredients: {
        fontFamily: 'Poly-Regular',
        fontSize: 18,
        marginVertical: 6,
    },
    ctnButtonAddToCart: {
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 28,
    },
    buttonAddToCart: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 20,
        width: 260,
        paddingVertical: 12,
        borderRadius: 24,
        backgroundColor: '#2c5d48',
    },
    textUtensils: {
        fontFamily: 'Poly-Regular',
        fontSize: 18,
        marginTop: 16,
        lineHeight: 26,
    },
    ctnNutrition: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 16,
        paddingHorizontal: 12,
        paddingVertical: 16,
        backgroundColor: '#fff5ea',
        borderRadius: 12,
        marginBottom: 28,
    },
    textNutition: {
        fontFamily: 'Poly-Regular',
        fontSize: 18,
        textAlign: 'center',
        marginVertical: 2,
    },
    ctnCookStep: {
        marginBottom: 32,
    },
    textStep: {
        fontFamily: 'Poly-Regular',
        fontWeight: 'bold',
        fontSize: 20,
        marginBottom: 12,
    },
    imgStep: {
        width: '100%',
        height: 240,
        borderRadius: 12,
        marginBottom: 16,
    },
    imgIcon: {
        width: 24,
        height: 24,
    },
    textIngreCook: {
        fontFamily: 'Poly-Regular',
        fontSize: 18,
        marginLeft: 16,
        lineHeight: 26,
        width: '85%',
    },
    textDesCook: {
        fontFamily: 'Poly-Regular',
        fontSize: 18,
        lineHeight: 26,
    },
    ctnComment: {
        paddingVertical: 16,
        paddingHorizontal: 16,
        flexDirection: 'row',
        width: '100%',
    },
    userComment: {
        width: '10%',
        marginRight: 16,
    },
    imgUserCmt: {
        width: 46,
        height: 46,
        borderRadius: 50,
        borderColor: '#ccc',
        borderWidth: 1,
    },
    ctnTextCmt: {
        width: '85%',
        height: 140,
        paddingHorizontal: 12,
        paddingVertical: 12,
        borderRadius: 20,
        borderColor: '#ccc',
        borderWidth: 1,
    },
    textCmt: {
        fontFamily: 'Poly-Regular',
        fontSize: 16,
        padding: 8,
        height: 60,
        lineHeight: 24,
    },
    buttonSend: {
        padding: 8,
        borderRadius: 20,
        backgroundColor: '#2c5d48',
        width: 72,
        position: 'absolute',
        bottom: 12,
        right: 12,
    },
    focusInput: {
        borderColor: 'blue',
        borderWidth: 0.5,
        borderRadius: 10,
    },
    ctnButtonCook: {
        position: 'absolute',
        bottom: 32,
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'center',
        zIndex: 100,
    },
    buttonStartCook: {
        paddingHorizontal: 20,
        width: 220,
        paddingVertical: 12,
        borderRadius: 24,
        backgroundColor: '#2c5d48',
    },
    textCooking: {
        fontFamily: 'Poly-Regular',
        fontSize: 18,
        color: '#fff',
        textAlign: 'center',
    },
    overlay: {
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        position: 'absolute',
        justifyContent: 'flex-end',
        backgroundColor: 'rgba(0, 0, 0, 0.4)',
        flexDirection: 'column',
    },
    ctnNotice: {
        position: 'absolute',
        top: 20,
        width: '100%',
        zIndex: 220,
        padding: 16,
        justifyContent: 'center',
        flexDirection: 'row',
    },
    notice: {
        paddingHorizontal: 20,
        paddingVertical: 10,
        width: 260,
        backgroundColor: '#f7dad596',
        borderRadius: 8,
    },
    textNotice: {
        fontFamily: 'Poly-Regular',
        fontSize: 18,
        textAlign: 'center',
    },
});

export default styles;
