import { Dimensions, StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backfaceVisibility: '#f5f5f5',
    },
    overlay: {
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        position: 'absolute',
        justifyContent: 'flex-end',
        backgroundColor: 'rgba(0, 0, 0, 0.4)',
        flexDirection: 'column',
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 8,
        marginTop: 24,
    },
    ctnIcon: {
        width: 46,
        height: 46,
        borderRadius: 50,
        borderColor: '#737070',
        borderWidth: 1,
        backgroundColor: '#fff',
        justifyContent: 'center',
        alignItems: 'center',
    },
    textHeader: {
        fontSize: 28,
        fontFamily: 'Poly-Regular',
        color: '#000',
        fontWeight: 'bold',
    },
    body: {
        paddingHorizontal: 16,
    },
    ctnTimeFiled: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: '100%',
    },
    btnTimeFiled: {
        paddingTop: 10,
        paddingBottom: 20,
        borderBottomColor: '#ccc',
        borderBottomWidth: 1,
    },
    btnActive: {
        paddingTop: 10,
        paddingBottom: 20,
        borderBottomColor: '#da7e4f',
        borderBottomWidth: 2,
    },
    textTimeFiled: {
        fontSize: 18,
        fontFamily: 'Poly-Regular',
        color: '#000',
        fontWeight: 'bold',
        marginBottom: 6,
    },
    quantityRecipes: {
        fontSize: 16,
        fontFamily: 'Poly-Regular',
        color: '#6b6567',
    },
    ctnTime: {
        flexDirection: 'row',
        justifyContent: 'center',
        marginTop: 24,
        paddingBottom: 24,
    },
    displayTime: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '90%',
        paddingVertical: 12,
        paddingHorizontal: 16,
        backgroundColor: '#ddd',
        borderRadius: 20,
        alignItems: 'center',
    },
    timeText: {
        fontSize: 18,
        fontFamily: 'Poly-Regular',
        color: '#535353',
        fontWeight: 'bold',
    },
    ctnEllipsis: {
        padding: 12,
        paddingHorizontal: 16,
        backgroundColor: '#ddd',
        borderRadius: 50,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    content: {
        marginTop: 12,
        paddingBottom: 100,
        paddingHorizontal: 16,
    },
    ctnItemEmpty: {
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 40,
    },
    imageEmpty: {
        height: 120,
        resizeMode: 'contain',
    },
    textEmpty: {
        fontSize: 18,
        marginTop: 4,
        fontFamily: 'Poly-Regular',
        color: '#000',
        fontWeight: 'bold',
    },
    btnDiscovery: {
        width: 120,
        paddingVertical: 12,
        paddingHorizontal: 16,
        backgroundColor: '#458e6e',
        borderRadius: 20,
        marginTop: 20,
    },
    txtDiscovery: {
        fontSize: 16,
        fontFamily: 'Poly-Regular',
        color: '#fff',
        fontWeight: 'bold',
        textAlign: 'center',
    },
    subText: {
        fontSize: 16,
        fontFamily: 'Poly-Regular',
        color: '#65676b',
        textAlign: 'center',
        marginHorizontal: 20,
        lineHeight: 20,
        marginTop: 10,
    },
    category: {
        fontFamily: 'Poly-Regular',
        fontSize: 20,
        fontWeight: 'bold',
        marginBottom: 12,
    },
    ctnItem: {
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 10,
        justifyContent: 'space-between',
        flexDirection: 'row',
        marginBottom: 12,
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.2,
        shadowRadius: 4,
    },
    itemLeft: {
        flexDirection: 'row',
        width: '60%',
    },
    imageDish: {
        width: 60,
        height: 60,
        borderRadius: 8,
        marginRight: 12,
    },
    textDish: {
        fontFamily: 'Poly-Regular',
        fontSize: 18,
        fontWeight: 'bold',
        textAlign: 'left',
        marginBottom: 8,
    },
    timeCook: {
        fontFamily: 'Poly-Regular',
        fontSize: 16,
        color: '#65676b',
        marginLeft: 4,
    },
    labelDish: {
        fontFamily: 'Poly-Regular',
        fontSize: 14,
        color: '#65676b',
        fontWeight: 'bold',
        color: '#458e6e',
    },
    itemRight: {
        flexDirection: 'column',
        justifyContent: 'space-between',
        alignItems: 'flex-end',
    },
});

export default styles;
